on: push
name: CI
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Lint
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: yarn lint
      - name: Test
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: yarn test
